image: node:8

stages:
  - install
  - build
  - deploy

before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in $SSH_DEPLOY_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Assuming you created the SSH_DEPLOY_TARGET_HOST_KEY variable, uncomment the
  ## following two lines.
  ##
  - echo "$SSH_DEPLOY_TARGET_HOST_KEY" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

install:
  tags:
    - docker
  stage: install
  only:
    - master
  script:
    - 'yarn install'
  artifacts:
    paths:
      - 'node_modules/'
    expire_in: 1 day

build:
  tags:
    - docker
  stage: build
  only:
    - master
  dependencies:
    - install
  script:
    - 'node ./build/build.js --vendor chrome --env production --pack'
    - 'node ./build/build.js --vendor edge --env production --pack'
    - 'node ./build/build.js --vendor firefox --env production --pack'
    - 'node ./build/build.js --vendor opera --env production --pack'
  artifacts:
    paths:
      - 'dist/'
      - 'packages/'
    expire_in: 1 week

deploy:
  tags:
    - docker
  stage: deploy
  only:
    - master
  dependencies:
    - build
  artifacts:
    paths:
    - 'packages/'
    expire_in: 1 week
  script:
    - 'ssh imarex@vwebbn002.rzbn.infon "mkdir -p /var/www/html/imarex.infonline.de/extensions"'
    - 'scp -P22 -r packages/* imarex@vwebbn002.rzbn.infon:/var/www/html/imarex.infonline.de/extensions'
