image: node:latest

stages:
  - install
  - build
  - deploy

install:
  tags:
    - docker
  stage: install
  only:
    - master
  script:
    - 'yarn install'
  artifacts:
    paths:
      - 'node_modules/'
    expire_in: 1 day

build:
  tags:
    - docker
  stage: build
  only:
    - master
  dependencies:
    - install
  script:
    - 'yarn run build:staging'
  artifacts:
    paths:
      - 'dist/'
    expire_in: 1 week

deploy:
  tags:
    - docker
  stage: deploy
  only:
    - master
  dependencies:
    - build
  artifacts:
    paths:
    - 'packages/'
    expire_in: 1 week
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_DEPLOY_TARGET_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'ssh imarex@vwebbn002.rzbn.infon "mkdir -p /var/www/html/dmr.infonline.de/extensions"'
    - 'ssh imarex@vwebbn002.rzbn.infon "rm -rf /var/www/html/dmr.infonline.de/extensions/*"'
    - 'scp -P22 -r dist/packages/* imarex@vwebbn002.rzbn.infon:/var/www/html/dmr.infonline.de/extensions'
