image: node:latest

stages:
  - install
  - build
  - deploy_staging
  - deploy_production

install:
  tags:
    - docker
  stage: install
  only:
    - master
    - staging
  script:
    - 'yarn install'
  artifacts:
    paths:
      - 'node_modules/'
    expire_in: 1 day

build:
  tags:
    - docker
  stage: build
  only:
    - master
    - staging
  dependencies:
    - install
  script:
    - 'yarn run build:staging'
  artifacts:
    paths:
      - 'dist/'
    expire_in: 1 week

deploy_staging:
  tags:
    - docker
  stage: deploy_staging
  only:
    - staging
  dependencies:
    - build
  artifacts:
    paths:
    - 'dist/'
    expire_in: 1 week
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_DEPLOY_TARGET_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'ssh imarex@vwebbn002.rzbn.infon "mkdir -p /var/www/html/dmr.infonline.de/extensions"'
    - 'ssh imarex@vwebbn002.rzbn.infon "rm -rf /var/www/html/dmr.infonline.de/extensions/*"'
    - 'scp -P22 -r dist/packages/* imarex@vwebbn002.rzbn.infon:/var/www/html/dmr.infonline.de/extensions'

deploy_production:
  tags:
    - docker
  stage: deploy_staging
  only:
    - master
  dependencies:
    - build
  artifacts:
    paths:
      - 'dist/'
    expire_in: 1 week
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_DEPLOY_TARGET_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'ssh deploy@vdmrbn001.infon "mkdir -p /usr/share/nginx/dmr-frontend/extensions"'
    - 'ssh deploy@vdmrbn001.infon "rm -rf /usr/share/nginx/dmr-frontend/extensions/*"'
    - 'scp -P22 -r dist/packages/* deploy@vdmrbn001.infon:/usr/share/nginx/dmr-frontend/extensions'
